### ISSUE TITLE
Entries are not really be created

### ISSUE THREAD

**Issue by alfredosalzillo** [davidesantangelo/datoji#2]
I'm trying to create entries using the create bulk API.
The API call return me the ids of the entries created, but if I try to read them, using any of the find APIs I receive an empty set.
Also, the get of the pack, return an empty set.

**Comment by davidesantangelo** [comment]
Thanks Alfredo 

I found the bug. Fixo now!

**Comment by davidesantangelo** [comment]
fixed https://github.com/davidesantangelo/datoji/commit/e6399d79b97a2645925a8231974dac4ae2e00625
